### ISSUE TITLE
Intrusive Elements

### ISSUE THREAD

**Issue by alan-balding** [w3c/html#1091] opened 2017-11-29 11:11 UTC
I am concerned about some websites use of video and audio elements of HTML5. For instance autostarting video, maxing the sound output and freezing the controls until the video has run to the end. I have searched in vain trying to find how to work round these blatant attempts to take away my ability to control my own  devices and browsers. I can give you examples of such behaviour but I am hopeful that the developers of HTML5 are already aware of the abuse of their code and are working on or have already found a solution. I would love to hear about this topic from anyone involved.

**Comment by LJWatson** [comment] 2017-11-29 12:07
The HTML elements don't tend to be the cause of these problems. Neither the `audio` or `video` element autoplays by default, and the [HTML spec](http://w3c.github.io/html/semantics-embedded-content.html#ready-states) advises user agents to honour user preferences over the presence of the `autoplay` attribute:
<"NOTE: User agents do not need to support autoplay, and it is suggested that user agents honor user preferences on the matter. Authors are urged to use
the autoplay attribute rather than using script to force the video to play, so as to allow the user to override the behavior if so desired."<

We could add a note to the spec though, that cautions against using autoplay and other hijacking practices, for reasons of good accessibility and/or usability.

**Comment by alan-balding** [comment] 2017-11-29 16:31
As I thought,  you are just trusting the page authors to be honourable. Oh dear, some are already betraying your trust. Is there a way, for example, that a users browser preference could be set to  intercept a video.ended = false message on its way back to the server and transmit a video .ended = true.  This would give control back to any user who desired not to be forced to watch a video in its entirety. Thank you for your rapid response.

**Comment by edent** [comment] 2017-11-29 16:45
Most browsers have a way for you, the user, to turn off autoplay. For example:

* https://support.apple.com/en-gb/guide/safari/stop-autoplay-videos-ibrw29c6ecf8/mac
* https://support.mozilla.org/en-US/questions/1141200
* https://www.theverge.com/2017/9/15/16311310/google-chrome-autoplay-videos-january

**Comment by alan-balding** [comment] 2017-11-29 18:39
Terrence is of course right but not allowing the video to load or autostart will still result in some web pages stalling. The reason is that in these cases the web server sends out a request and awaits a reply from the browser that the video has played to the end before allowing further progress.

I am now informed that setting up a local proxy that will change a video.ended request reply to True in all cases on that website. Such a proxy is I am informed is called the BURP SUITE. I am now looking into this as it seems a complete answer. If any reader knows how to do this it will save me having to climb a fairly steep learning curve for me. Thank you all for your help

**Comment by LJWatson** [comment] 2017-12-13 13:59
It isn't clear what, if anything, can be done within the spec to address this concern beyond the note I suggested previously?

**Comment by chaals** [comment] 2017-12-13 16:16
When to send an untrue statement that a resource has finished playing seems like a user agent issue. I suggest we close this for the specification.

**Closed as completed** 2017-12-14 09:14 UTC
