### ISSUE TITLE
A stale link, a missing attribute description, and an inverted content model condition.

### ISSUE THREAD

**Issue by tzik** [w3c/html#62] opened 2016-02-04 14:41 UTC
Translated from [a post of a local developer community by mount-root-yy](https://groups.google.com/d/msg/html5-developers-jp/TFXiXjWtU20/4pMzXS4lGAAJ).
- On [the Guidance for conformance checkers of <img>](https://w3c.github.io/html/semantics.html#guidance-for-conformance-checkers), the second bullet item mentions the title attribute, but the link is not related to it.
- "datetime-local" is missing on [the list of valid type attributes of <input>](https://w3c.github.io/html/semantics.html#attr-input-type-keywords)
- [The content model of <time>](https://w3c.github.io/html/semantics.html#the-time-element) with a datetime attribute should be "phrasing content" and one without datetime attribute should be "Text" according to the following statement: "A time element that does not have a datetime content attribute must not have any element descendants."

**Comment by foolip** [comment] 2016-02-06 19:26
I keep an eye on this repo to see what issues also apply to the [WHATWG upstream](https://github.com/whatwg/html), some pointers:
- The `<img>` problem looks like fallout of changes around `title` on `<img>`
- "datetime-local" is not missing in https://html.spec.whatwg.org/multipage/forms.html#attr-input-type-keywords, perhaps it's a failed cherry-pick of https://github.com/w3c/html-old/commit/3e5df1ee1aebed37571a23c9b62adc74a92a04b9
- I've fixed the content model of `<time>` in whatwg/html, see above.

The initial import a023b06e45851e5053e59376da19cd76a6cb7800 most resembles https://github.com/whatwg/html/commit/8558f93f86a8a910fa23d961e271e7333e16170e, but with no history it's difficult to say what changes are deliberate and which are accidental.

**Comment by travisleithead** [comment] 2016-05-20 23:11
Well, we've got `datatime-local` back (reverted the 5.0 change due to wide implementation support), and I've got the inverted `<time>` content model fix ready, but not sure what to do with the `title` attribute on `<time>`. Hopefully @stevefaulkner or @LJWatson can lend some thoughts? PR on it's way...

**Comment by chaals** [comment] 2016-05-21 08:31
Looking at the bit about `<img title`, the issue is that in the second bullet of [guidance for conformance checkers about images](https://w3c.github.io/html/semantics-embedded-content.html#guidance-for-conformance-checkers) there is a link whose text is "as described above". What is "described above" is some stuff apparently all about `figure` elements.

In any event, the entire section is too long, hard to understand, and has a bunch of issues against it.

We should look at the ARIA definition of accessible names, and trim this section down to something manageable and clear that matches that.

Browsers only do a couple of things to help users find text that supplements images, but conformance checkers and tools for authors are also important use cases for this section, as are individual authors.

**Comment by chaals** [comment] 2016-05-21 08:34
Looking at the bit about `<img title`, the issue is that in the second bullet of [guidance for conformance checkers about images](https://w3c.github.io/html/semantics-embedded-content.html#guidance-for-conformance-checkers) there is a link whose text is "as described above". What is described above is some stuff apparently all about `figure` elements.

In any event, the entire section is too long, hard to understand, and has a bunch of issues against it.

We should look at the ARIA definition of accessible names, and trim this section down to something manageable and clear that matches that.

Browsers only do a couple of things to help users find text that supplements images, but conformance checkers and tools for authors are also important use cases for this section, as are individual authors.

**Comment by chaals** [comment] 2016-05-21 08:35
The acknowledgements should also mention mount-root-yy - @tzik do you know a real name for that user?

**Comment by stevefaulkner** [comment] 2016-05-23 13:35
Note: have updated conformance checker section https://github.com/w3c/html/commit/9a8cb41988eb45acf058c9cc7e1d7c3ab26955dc to reflect, details in commit notes.

**Comment by chaals** [comment] 2016-06-01 22:34
I think this is now all done except getting the acknowledgements. Closing

**Closed as completed by chaals** 2016-06-01 22:34 UTC
