### ISSUE TITLE
[HTML 5.1 2nd edition] section 8.2.3.2 wrong id for defined term

### ISSUE THREAD

**Issue by waldbaerkoch** [w3c/html#1079] opened 2017-11-13 14:31 UTC
HTML 5.1 2nd edition: In section '8.2.3.2 The stack of open elements' both the definition of **have a particular element in list item scope** and **have a particular element in select scope** have the same `id`: "have-an-li-element-in-list-item-scope". This results in erronous links: in section '8.2.5.4.7. The "in body" insertion mode' / 'An end tag whose tag name is "li"' the term "have an li element in list item scope" is linked to **have a particular element in select scope**  instead of **have a particular element in list item scope**.

This does **not** appear in the HTML 5.2 Proposed Recommendation.

**Comment by LJWatson** [comment] 2017-11-13 14:57
Thanks for letting us know @@waldbaerkoch. Unfortunately we're unable to change the 5.1 specification because it's reached Recommendation status.
Good to know the problem is resolved in HTML5.2, and also I believe in the [HTML5.3 Editor's Draft](https://w3c.github.io/html)

**Closed as completed by LJWatson** 2017-11-13 14:57 UTC
