### ISSUE TITLE
sectioning roots and the document outline

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html#806] opened 2017-02-22 10:12 UTC
The currently defined [sectioning roots](http://w3c.github.io/html/sections.html#sectioning-roots) produce somewhat bizarre results. In a [test page](https://output.jsbin.com/wulimo) I have included examples of all sectioning roots (except `dialog` which I can understand as not contributing to the doc outline as it is a pseudo window)

The resulting HTML5 document outline for the test page is [body element with no heading] None of the headings in the document are exposed in the document outline as per the algorithm. But as far as UA CSS is concerned they are still styled as headings of appropriate rank.

**Comment by jonathantneal** [comment] 2017-02-23 05:06
This may be related. https://github.com/validator/validator/commit/0789dc8b03bee75ba82f12af20b9785a161557bc

**Comment by stevefaulkner** [comment] 2017-02-23 06:34
@jonathantneal yes I discussed this with @sideshowbarker

**Comment by stevefaulkner** [comment] 2017-02-23 06:55
@jonathantneal yes it is

**Comment by AmeliaBR** [comment] 2017-02-26 21:08
For `blockquote` and `figure`, I think encapsulating the headings still makes sense.  If you were using those elements as intended in a larger document, any nested headings would not be part of the main document outline, they would be part of the quote or example.

The same is probably true for `td` when used semantically, although layout tables confuse the matter considerably.

However, for `fieldset` and `details`, I don't quite understand the purpose of the encapsulation.  

If you have a long form and use `fieldset` to group it into logical sections, I would expect the same outline as if the form was divided with `section` elements.  I can't see why someone would use `h1`, `h2`, etc. inside a form and not intend them to be treated as ordinary headings.

Similarly for `details`: The accordion pattern with headings inside of `summary` is very much established as a way to collapse sections or asides.  Yes, there are currently other accessibility issues with how to expose details/summary (if `summary` is exposed as a button containing a text label, instead of as a "disclosure triangle" button adjacent to text, the headings inside of `summary` may be obscured from the perspective of accessibility APIs).  But if details/summary should never be used for section-level content, a massive re-education campaign will be required.  So long as they continue to work (for most users) when used this way, they will continue to be used this way.

**Comment by patrickdark** [comment] 2017-02-28 22:21
@AmeliaBR I agree with you on `details`. I currently use XSLT to automatically transform all `<section><h1/><section>` constructs into `<section><details><summary><h1/></summary></details></section>`. Ditto for `nav` and both elements containing `hgroup`. Having `details` as a sectioning root basically means that my documents only have page headings as far as such an outline model is concerned and I need to go back to using JavaScript to show/hide...

 `fieldset` doesn't make sense with heading elements if you're using them to mark singular fields and inseparable fields like checkbox and radio button groups. I can see how someone could understand them to be equivalent to `section` elements though. (Kind of a moot point, however, since people are going to stay away from `fieldset`/`legend` until they're made fully stylable.)

**Comment by siusin** [comment] 2019-07-29 15:37
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.

**Closed as completed by siusin** 2019-07-29 15:37 UTC
Labels: bug
