### ISSUE TITLE
Focus ring rendering guidance

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#868] opened 2017-04-06 12:55 UTC
Would it be useful to add something about focus ring behaviour to [10 Rendering](https://www.w3.org/TR/html52/rendering.html#rendering)?

**Comment by patrickhlauke** [comment] 2017-04-06 13:02
from memory (i'm sure i missed out something or misremembered, not had a chance to retest), in the past all browsers used to apply the default focus ring/outline when an element received focus, always. this is the root cause of the css reset `outline:none`. see https://24ways.org/2009/dont-lose-your-focus/

more recently though, browsers started applying heuristics to determine when to show or not show the default focus ring/outline. the current most popular browser heuristics:

- when a focusable control (link, button, select, input, image map area, etc) receives focus via the keyboard, always show the default outline indicator (e.g. the dotted outline in firefox, the glowy blue outline in chrome, etc)
- if a focusable control receives focus as the result of a mouse or touch action, only show the outline for a few (like text inputs) by default, otherwise no default outline indicator
- firefox adds a heuristic: if the user has at any prior point used the keyboard/TAB to interact with the page, always show the default focus outline for all elements that normally receive focus, even if it's a result of a mouse/touch/etc (first time I heard of this was here https://www.sitepoint.com/when-do-elements-take-the-focus/)
- and chrome is the one that also shows default focus, strangely, when a tabindex=-1 arbitrary element receives focus, regardless of how (from memory, this may have changed in recent versions)
- if there are any `:focus` styles explicitly defined, then all browsers also apply the styles regardless of whether result of keyboard or mouse or touch etc

to more systematically work around this, there's the proposed `:focus-ring` pseudo class https://drafts.csswg.org/selectors-4/#the-focusring-pseudo which can be polyfilled (for the most part) today https://github.com/WICG/focus-ring (see also video explainer https://www.youtube.com/watch?v=ilj2P5-5CjI)

however, getting back to the default browser behavior for when to show the default focus ring, yes it would be good to document at least the "this always happens" part, and perhaps add a non-normative note that browsers MAY also apply heuristics (mainly to avoid showing default outline as result of mouse/touch)

**Comment by iandevlin** [comment] 2017-04-06 13:11
Just to verify, @patrickhlauke's point about Chrome's strange adding of the focus ring on elements that have a `tabindex="-1"` still happens (when `.focus()` is called on the element or the mouse clicks on the element), and also in Firefox and Safari (they're the only ones I have tested).
It appears to do it on any element, e.g. `div`, `input`, `button`.

**Comment by TakayoshiKochi** [comment] 2017-04-09 15:03
It seems Firefox doesn't draw focus ring when `<div tabindex="-1">...</div>` gets focus (via `.focus()` or mouse click), while Chrome does.

Click on 'bbb' below to test:
http://jsbin.com/wolivovocu/edit?html,output

`tabindex="-1"` means that the element is actually focusable and can get focus.  Once it gets focus, `:focus` pseudo class is applied as specified in UA stylesheet, which is expected.

So the "strange" statement is for how UA stylesheet specifies this style in Chrome?

**Comment by iandevlin** [comment] 2017-04-10 07:07
@TakayoshiKochi I disagree, Firefox is indeed drawing a focus ring when the element receives focus from a mouse or from `.focus()`. I can see it on Firefox 52.0.2 on MacOS Sierra 10.12.4.

But it doesn't appear to do it on Windows!

**Comment by LJWatson** [comment] 2017-06-23 14:02
@Patrick_H_Lauke would you be able to propose some words/default styling guidance for this?

**Comment by chaals** [comment] 2018-06-19 13:03
@patrickhlauke ping?

**Comment by siusin** [comment] 2019-07-29 15:32
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.

**Closed as completed by siusin** 2019-07-29 15:32 UTC
Labels: help wanted, a11y
