### ISSUE TITLE
Figure out whether <rp> should auto-close other ruby elements

### ISSUE THREAD

**Issue by travisleithead** [w3c/html#288] opened 2016-04-27 22:04 UTC
Moved from Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26424

@darobin, @kojiishi, @fantasai, @r12a 

> > So, I fixed rp to not autoclose rtc (in c61397b). However I'm confused about
> > the rest of the discussion about having it not autoclose anything?
> 
> rp to auto-close rtc is a change introduced early this year as you know, and broke at least one existing site though the site is not valid.
> 
> rp to auto-close rt is a change introduced years ago, in earlier HTML5 WD, and broke some existing sites. Again, though the sites are not valid, IE6-9 renders such HTML as ruby, and the number of sites the change broke is probably more than the above. Two examples of such sites are:
> - http://reference.sitepoint.com/html/rp
> - http://www.w3schools.com/TAgs/tag_rp.asp
>   but searching in github gives a lot more examples.
> 
> So if we change rp not to auto-close rt, it'd be a breaking change against early and current HTML5, but is more compatible with IE6-9. The question here is which is more beneficial for existing contents and for future authors. My opinion is it's better to change not to auto-close rt. It's unlikely to break existing contents, it saves sites that were broken by early/current HTML5 spec, and shouldn't harm future authors almost at all.
> 
> Now we started to wonder, should rp auto-close rb or any other elements that have implied end tags.
> 
> Benefits for rp to auto-close rb/others:
> - can't think much, little to zero
> 
> Downside for rp to auto-close rb/others:
> - rp behaves differently from any other tags (if we change it not to auto-close rt), so it requires additional "if" statement in the spec and code.
> - It will auto-close any new elements we may add in future.
> 
> Benefits for rp not to auto-close rb/others:
> - Saves sites created for IE6-9.
> 
> Downsides for rp not to auto-close rb/others:
> - Breaks sites created for HTML5 and relies on rp's auto-closing behavior. Sites that use "rp { display: none; }" are ok, but wchen found some sites use "ruby > rp { display: none; }" so such sites may break if they omit closing tags.
> 
> By reviewing this, it looks to me that benefits to auto-close and downsides not to auto-close look much less than benefits not to auto-close and downsides to auto-close.
> ---
> 
> Note that the site who reported an issue [1] doesn't render as ruby either,
> and he uses display:table-cell technique to look like ruby. I don't think
> there are many sites that use the technique, but I might try to find rbc and
> rtc to double-check later.
> 
> [1] http://ikilote.net/fr/Collection/Personnalit%C3%A9.html?id=394
> 
> In fact, I took this technique to my website by taking example on other websites. (Besides, it also works for IE9 and superior, but not IE8 and earlier)

**Comment by kojiishi** [comment] 2016-04-28 02:16
I believe this has been fixed in the spec both in w3c/whatwg, web-platform-tests, WebKit, Blink, and Gecko.

**Comment by travisleithead** [comment] 2016-05-02 15:27
Super (I wasn't sure when reading the parsing algorithm). Not fixed in Edge yet?

**Comment by chaals** [comment] 2016-05-10 19:10
Check what @kojiishi said, hopefully we can close this.

**Comment by kojiishi** [comment] 2016-05-29 09:30
@travisleithead 

> Super (I wasn't sure when reading the parsing algorithm). Not fixed in Edge yet?

I believe Edge has never be affected, since this issue was caused by a spec change in early HTML5 and [discovered by implementing it in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1042885). Gecko/Blink/WebKit were affected because they followed the early spec.

The [minimal test case](http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=3075) indicates that Edge is not affected (rp staying inside rtc means it doesn't auto-close.)

Note that only Edge does not render [the reported site in the Gecko bug](http://ikilote.net/fr/Collection/Personnalit%C3%A9.html?id=394) correctly; the ruby is rendered on the right of the base. According to the DOM Explorer, the DOM tree is correct, so it's probably rendering issue, not a parser issue.

**Comment by arronei** [comment] 2017-03-13 21:48
Will be wrapped up in new merge process.

**Closed as completed by arronei** 2017-03-13 21:48 UTC
Labels: i18n-comment
