### ISSUE TITLE
Input type currency

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#939] opened 2017-05-29 16:49 UTC
Migrated from [Bugzilla 30035](https://www.w3.org/Bugs/Public/show_bug.cgi?id=30035)

From the original:
>"Input type of number is good for small numbers, but for currency amounts over 999 the unformatted number being input is hard to read. Imagine having to type in 45,000,000 without the visual feedback of the commas.

We can accomplish this with JavaScript (on an "input" event listener, e.g.):
	   function localizeCurrency() {
			var oldValue = this.value;
			this.rawValue = oldValue ? parseInt(oldValue.replace(/,/g, '')) : 0;
			if (oldValue) {
				var newValue = parseInt(oldValue.replace(/,/g, '')).toLocaleString();
				var caretPos = this.selectionStart - (oldValue.length - newValue.length);
				this.value = newValue;
				this.setSelectionRange(caretPos,caretPos);
			}
		}

But it requires an input type of "text" (to allow the commas to appear), and it would be much better to have this in the HTML itself.
<input type="currency" locale="usd">

As I type...what should appear
1           $1.00
10          $10.00
1000        $1,000.00
450000      $450,000.00">

**Comment by jpdevries** [comment] 2017-05-30 19:28
Another reason it seems `<input type=currency>` would be ideal (as opposed to JavaScript) is if it were standardized it would integrate with i18n. In America we write $1,000.35 but in the EU it would be €1.000,35...

**Comment by SebastianZ** [comment] 2017-06-01 06:31
> in the EU it would be €1.000,35...

Fwiw, in Germany (and probably some other European countries) it's even 1.000,35 €, with the Euro sign [after the number](https://de.wikipedia.org/wiki/Eurozeichen) and a [non-breaking space between them](https://de.wikipedia.org/wiki/Schreibweise_von_Zahlen#Ma.C3.9Feinheit).

Sebastian

**Comment by agcolom** [comment] 2017-06-01 06:52
@SebastianZ I can confirm that this is the case in France as well: 1.000,35 €
Other currencies such as CHF are normally also written with the currency sign after the number and a non-breaking space.

**Comment by LJWatson** [comment] 2017-07-04 19:40
Do we have any data on how often developers are using a workaround? Are there any standard polyfills/libraries/scripts that people are using?

**Comment by siusin** [comment] 2019-07-29 15:13
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.

**Closed as completed by siusin** 2019-07-29 15:13 UTC
Labels: Feature request
