### ISSUE TITLE
Type attribute for ordered lists should be obsolete but conforming

### ISSUE THREAD

**Issue by rebecaruiz** [w3c/html#341] opened 2016-05-04 20:37 UTC
Since there is a stable property `list-style-type` in CSS with many available values, the values `1`, `a`, `A`, `i` and `I` correspondant to CSS properties `decimal`, `lower-latin` / `lower-alpha`, `upper-latin` / `upper-alpha`, `lower-roman` and `upper-roman` [should become obsolete but conforming](http://w3c.github.io/html/grouping-content.html#elementdef-ol).
The `type` attribute is currently [obsolete](https://www.w3.org/TR/html-markup/ul.html) for unordered lists.
There are [more styling options](https://www.w3.org/TR/CSS22/generate.html#list-style) for ordered lists in CSS than in HTML, such as greek alphabet or armenian numbering. Maybe more options could be added to the CSS spec (for instance, `upper-greek` is currently missing in CSS). Internationalization could be improved by providing certain language-specific CSS presets for ordered lists.

Please tell me if I made any mistake, this is the first issue that I post!

Cheers,
Rebeca Ruiz

**Comment by chaals** [comment] 2016-05-04 22:23
If we make the attribute obsolete, authors can use CSS. I think it would be feasible to provide better language-based defaults, similar to the CSS for `q` elements, in browsers.

@rebecaruiz The issue seems reasonable as filed...

**Comment by r12a** [comment] 2016-05-05 05:16
https://www.w3.org/Bugs/Public/show_bug.cgi?id=26417 raises the same question. (It doesn't seem to have been moved to github issues.)

Note, however, my further question there: 

> Or is this intentionally kept as a way to allow a minimal set of 'semantically' differentiated lists, that will work if CSS is not present? If so, perhaps we should add a brief note to explain that, and mention that you can do much more using CSS.

@rebecaruiz , note that [CSS3](https://www.w3.org/TR/css-counter-styles-3/) specifies more counter styles than CSS2, many of which are [already supported by more than one browser](https://www.w3.org/International/tests/repo/results/predefined-counter-styles), but also provides a mechanism for defining your own styles, such as upper-greek (although we haven't been able to find evidence that upper-greek is something that Greeks want to use).  Note also that the language-specific CSS presets for ordered lists you asked about [are available](https://www.w3.org/TR/predefined-counter-styles/).

**Comment by rebecaruiz** [comment] 2016-05-05 07:08
@r12a 

> [https://www.w3.org/Bugs/Public/show_bug.cgi?id=26417](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26417) raises the same question. (It doesn't seem to have been moved to github issues.)

So that's the reason why I vaguely remembered I had read about something similar but didn't find any thread about it.

> Or is this intentionally kept as a way to allow a minimal set of 'semantically' differentiated lists, that will work if CSS is not present? If so, perhaps we should add a brief note to explain that, and mention that you can do much more using CSS.

I do not think that the type of ordered lists is a semantic feature. Augustus was the first Roman emperor and it does not matter if you count them with Roman or decimal numbering. (It would be different if we started to count emperors since the third one, so the attribute `start` is semantically relevant in ordered lists). It's like thinking that unordered lists change substantially depending on the items being rendered with discs, circles or squares. Type attribute was declared obsolete for them and I think it is a good choice because it is all about decoration.

> note that CSS3 specifies more counter styles than CSS2, many of which are already supported by more than one browser, but also provides a mechanism for defining your own styles,

Great that it already existed. Shame on me for not having found it.

> but also provides a mechanism for defining your own styles, such as upper-greek (although we haven't been able to find evidence that upper-greek is something that Greeks want to use) […] Note also that the language-specific CSS presets for ordered lists you asked about are available.

Upper-greek may be good for academic writings, I was not thinking of modern Greek citizens at that moment. If there are already language-specific presets that's great news.

So, given that i18n features do already exist for `list-style-type`, the proposal in the title for setting `type` attribute obsolete but conforming remains the same. Do you think it would be a good choice?

Cheers

**Comment by plehegar** [comment] 2016-05-05 10:44
Side comment: 21 bugs are yet to be moved in bugzilla https://www.w3.org/Bugs/Public/buglist.cgi?product=HTML.next&resolution=--- and it includes https://www.w3.org/Bugs/Public/show_bug.cgi?id=26417 . So, we didn't loose that one.

**Comment by unor** [comment] 2016-05-05 13:02
@rebecaruiz 

> I do not think that the type of ordered lists is a semantic feature.

The spec gives an example for a semantic reason ([HTML5: `ol` →`type`](https://www.w3.org/TR/2014/REC-html5-20141028/grouping-content.html#attr-ol-type)):

> […] in the cases where that matters (e.g. because items are to be referenced by their number/letter).

If referencing items via "a.", "b.", "c." in the text, but not using the `type` value `a` for that list, it will be confusing for users using UAs without CSS support.

**Comment by prlbr** [comment] 2016-05-07 21:55
+1 @unor 

I’ve made a quick test page https://prlbr.de/2016/05/listtest.html and while the lists using `type='…'` show up as intended in Lynx 2.8.9dev.6, the lists using `style='list-style-type:…'` do not.

I’m a developer of a lightweight markup-language to HTML converter which uses HTML’s type attribute deliberately. We’ve switched from the CSS variant to the type attribute in the past and one reason was that it works in UAs without CSS support. Am I right to assume that this also affects assistive technology for visually impaired users?

Please do not deprecate it.

**Comment by r12a** [comment] 2016-05-11 15:32
If you are using counters in your text to refer back to your list, this is helpful perhaps where you use European decimals, Roman numerals or English alphabets for your list counters,.  Problem is, it's not so useful where you use ideographic, cyrillic, or other counters in your list.

Various thoughts spring to mind:
- we could add more list types. However, this is problematic because CSS now allows you to invent your own counter styles, so we couldn't cover all the bases.  Also, even with the list of supported styles we currently know about, it may be difficult to indicate which of a list of styles is meant using a single character - you'd probably want to use style names.
- you still have the problem of having to update your text if a new item is added to the list, which sort of spoils one of the benefits of using list elements.
- we could create a new element called something like `listref`, that refers to the list item using an id, and automatically replaces itself with whatever counter was used in to display the list item in question, whether CSS is available or not.  This seems a much cleaner approach, but takes this issue in a very different direction. (I doodled some [thoughts about this in our wiki](https://github.com/w3c/i18n-activity/wiki/Fallbacks-when-referring-to-a-list-item-in-a-list-with-non%E2%80%93Latin-counters).)

**Comment by rebecaruiz** [comment] 2016-05-12 14:23
@r12a
I think that the way you propose is an excelent path to follow. It's simple and elegant.

**Comment by chaals** [comment] 2016-05-25 09:39
[discussion on mailing list](http://www.w3.org/mid/op.yh0h0fbks7agh9@widsith.local)

**Comment by chaals** [comment] 2016-05-25 09:50
The idea of a new element seems nice, except it's a big effort in practice.

I suspect we can get a long way with what we already have:

> Смотрите третье в списке

(Check out the third item)

Where the list is too long, or not stable enough, 

```
see the <a href="#interesting">interesting part</a> of the list
```

Which is what we do for example in referring to sections of HTML.

Recommending that **in general** people use CSS by default seems reasonable, though. And is editorial in nature…

**Comment by prlbr** [comment] 2016-05-25 11:08
How about adding more options to the type attribute to cover non-western enumeration? Like the current ones, they could be mapped to CSS properties in CSS supporting user agents, so implementation should be really simple for those agents. In user agents that don’t support CSS, an enhanced type attribute would bring the attribute’s benefits to those that don’t use western enumeration symbols.

Superficially this might seem redundant, but CSS is about (presentational) styles, and list numbering is not always just that, as demonstrated by referencing items by their “number” from within the text. For example, Wikipedia uses lists for footnotes.

Here’s another example: The following page contains the first few sections of Germany’s animal protection law and uses lists: http://www.uni-mainz.de/FB/Medizin/nc-patho/tiersch/01_03.htm
When a law has been passed by the parliament, it’s not a question of design anymore whether something is codified as “§ 2, Abs. **3**” or “§ 2, Abs. **c**”. The correct symbols are part of the legally binding text that is referenced in thousands of documents by various authors.

**Comment by dylanb** [comment] 2016-05-25 13:52
@chaals you sent an email to the WG list, can I summarize what I think you asked

Proposal 1: obsolete type and use CSS only
Proposal 2: leave type and suggest CSS as an alternative

**Comment by cheshrkat** [comment] 2016-05-25 13:57
FWIW I don't think the display of an OL's counters is "style", the case noted by @unor is a solid example of why - the counter of the list may in some cases be part of the document's content and meaning. It should survive whether read on screen, printed, copy&pasted, etc (the fact list counters are lost in some copy&paste actions should be considered a bug).

Basically I  think HTML should be able to provide complete and meaningful text documents without requiring CSS. We may not do so very often but the purpose of HTML is to mark up content after all.

**Comment by r12a** [comment] 2016-05-25 15:25
@cheshrkat how would you handle the issues described in https://github.com/w3c/html/issues/341#issuecomment-218496519?

@prlbr it may be significant that the Tierschutzgesetz doesn't actually use `<li>` for their lists.

list numbering does fall back to something without CSS.  It seems to me that the problem arises when you try to point to a specific list item from text using the counter in the list.  I suspect that _that's_ the part of this that's broken (ie. the reference).

**Comment by LJWatson** [comment] 2016-05-25 15:35
@prlbr
"Am I right to assume that this also affects assistive technology
for visually impaired users?"

Curiously it doesn't seem to, no. Screen readers recognise the list-style-type attribute and announce the list markers accordingly.

That said the ability to distinguish one `<ol>` from another when CSS is unavailable is important. If the content is syndicated to another site that uses different CSS, if someone uses personalised CSS, or if the content is converted into a format that doesn't take the CSS with it, then there is the possibility that the content will either become less meaningful or utterly broken.

**Comment by cheshrkat** [comment] 2016-05-25 15:47
@r12a 
- where the text doesn't need to match the counter, I think @chaals solution is fine (not that we couldn't use a range of richer in-document reference elements; but as he says new elements are relatively expensive)
- where the text DOES need to match the counter, to me the issue is about the stability of display rather than the potential for people to dig themselves into a hole with custom styles. I think it's reasonable to expect authors to choose a list style and free text content that match while they are authoring the document, if that's what they require (as opposed to breaking their requirement with a custom style they can't match).
- I don't have a philosophical problem with adding further non-custom types for use with the attribute.

**Comment by r12a** [comment] 2016-05-25 17:22
FYI only: 
just for a bit of background context, we maintain a document with a list of pre-built international counter styles for CSS users that reflect local requirements at [Custom Counter Styles](http://w3c.github.io/predefined-counter-styles/).  We expect the list to grow. Many of the styles are already supported by some major browsers, but that doesn't usually include Edge/IE, see a list at https://www.w3.org/International/tests/repo/results/custom-counter-styles

**Comment by rebecaruiz** [comment] 2016-05-25 21:43
@prlbr 

> When a law has been passed by the parliament, it’s not a question of design anymore whether something is codified as “§ 2, Abs. 3” or “§ 2, Abs. c”. The correct symbols are part of the legally binding text that is referenced in thousands of documents by various authors.

The symbol § is widely used to mark up sectioning in books since 19th century (and maybe earlier). This symbol is a typographical character used mainly to refer to a particular section of a document, such as legal code. The likely origin of the section sign is the digraph formed by the combination of two S glyphs (from the Latin _signum sectiōnis_). When duplicated, as §§, it is read as the plural "sections" (e.g. "§§ 13–21"), much as "pp." (pages) is the plural of "p." Markup language is an old invention. Centuries ago symbols like § or † were used for marking up sectioning and annotations whithin a text. Now we use HTML elements like `<section>` or `<a>` with the same purpose.
So if the symbol § is needed to be used within a list of laws, it is with the purpose of pointing to a specific section of the law. This symbol is like an anchor to a section. I would use something like `<a class="sectionsymbol" id="section2" href="source.html#section2">2</a>` to mark up the 2nd section in a law and display § via CSS. The section symbol was not designed for lists. It was made for sectioning and pointing to sections in a text.

**Comment by prlbr** [comment] 2016-05-25 22:16
@r12a and @rebecaruiz 

I see that my example of the [webpage with the law](http://www.uni-mainz.de/FB/Medizin/nc-patho/tiersch/01_03.htm) caused some confusion. I think the confusion is due to the fact that the webpage contains list-like things that do not use HTML ordered list markup. However, the webpage does indeed contain `<ol>` lists as well and those are the ones I was referring to. (You can view the source code and search for `<ol>` to find them.) But let’s abstract away from this particular webpage with its inconsistent markup. I hope it’s clear that in general the “numbering” of lists in laws is significant and not a matter of presentation.

**Comment by rebecaruiz** [comment] 2016-05-25 22:39
Following with the anchor issue…
Given the list of the first five chapters of _Don Quijote de La Mancha_:
1. Que trata de la condición y ejercicio del famoso hidalgo don Quijote de la Mancha
2. Que trata de la primera salida que de su tierra hizo el ingenioso don Quijote
3. Donde se cuenta la graciosa manera que tuvo don Quijote en armarse caballero
   3.1 Primera parte
   3.2 Segunda parte
4. De lo que le sucedió a nuestro caballero cuando salió de la venta
5. Donde se prosigue la narración de la desgracia de nuestro caballero

I may like to display Roman numbering and reorder the chapters via `value` and `start` attributes, reintroduced in HTML5:

```
<ol id="firstexample" class="Romanos">
    <li>Que trata de la condición y ejercicio del famoso hidalgo don Quijote de la Mancha</li>
    <li>Que trata de la primera salida que de su tierra hizo el ingenioso don Quijote</li>
    <li>Donde se cuenta la graciosa manera que tuvo don Quijote en armarse caballero</li>
    <li>De lo que le sucedió a nuestro caballero cuando salió de la venta</li>
    <li>Donde se prosigue la narración de la desgracia de nuestro caballero</li>
</ol>

<ol id "secondexample" class="Romanos" start="2">
    <li>Que trata de la primera salida que de su tierra hizo el ingenioso don Quijote</li>
    <li value="3">Donde se cuenta la graciosa manera que tuvo don Quijote en armarse caballero</li>
    <li>De lo que le sucedió a nuestro caballero cuando salió de la venta</li>
    <li>Donde se prosigue la narración de la desgracia de nuestro caballero</li>
</ol>
```

III. Donde se cuenta la graciosa manera que tuvo don Quijote en armarse caballero
    III.1. Primera parte
    III.2. Segunda parte
IV. De lo que le sucedió a nuestro caballero cuando salió de la venta
V. Donde se prosigue la narración de la desgracia de nuestro caballero

The author should be able to refer consistently to III.2 in both lists, the first which starts with the list item value set to 1 and the second which starts with the list item value set to 3.

The main reason to reintroduce value and start attributes for ordered lists in HTML5 was that these attributes are semantic. I agree, they are semantic. We should be able to point to a specific item by its order (implicit or explicit) in a list. We should be able to extract the actual value of a list item and refer to it with a markup like this:
`<a href="document.html§listiteminsidelist">anchor text</a>`
Where § (or any other character) is the implicit algorithmic identifier for the list item, unlike #, which refers to the explicit id attribute arbitrarily set by the author.

But this escapes from the scope.

I think it is reasonable to declare type attribute obsolete but conforming. Documents would not be broken but authors would be encouraged to use CSS for rendering when possible. Maybe later a new way of referring to items inside ordered lists could be developed.

**Comment by chaals** [comment] 2016-05-26 00:06
@dylanb yes, those are roughly the alternatives that I think make sense.

Where there is a list whose order is important, but there is no reason to suppose it will move, I think CSS is enough. The point of hypertext is that someone else might want to point into the list, which is why finding what an annotation refers to if there are slight changes in content is such a key to the work on annotations. Which is an admission that this case is far from clearly defined.

Where there is a semantic reference to a particular item in the list, being able to give it an _anchor_ seems valuable. Something HTML has enabled since the beginning.

It seems that there are valid use cases for `type`, so we should not make it obsolete. There are also valid use cases for a list that needs ordering, but where the precise form of that is unimportant, and CSS is probably the sensible approach.

And there are apparently good reasons to try and extend the list of values acceptable for `type` - which means hammering on browsers to see how far we can do that in reality…

**Comment by r12a** [comment] 2016-05-26 11:52
> And there are apparently good reasons to try and extend the list of values acceptable for type - which means hammering on browsers to see how far we can do that in reality…

@chaals if i understand correctly, you mean to get browsers to recognise more of the labels defined by CSS Counter Styles(?) Problem is, even that longish list is only a subset of the styles [defined elsewhere](http://w3c.github.io/predefined-counter-styles/), and that list is expected to grow also ([example](https://github.com/w3c/predefined-counter-styles/issues/3)), and in fact CSS expects people to want to tailor and create counter-styles adhoc.  So i'm not sure how successful extending the list of values that are acceptable would be.

**Comment by prlbr** [comment] 2016-05-26 12:50
It’s cool that you can define your own list styles in CSS, but concerning a possible extension of numbering types avaliable for `<ol type="…">`, I think it would be sufficient to add types that are actually widely used in publications.

How do we get data on actual need/use? Or would it be better to wait until additional types are requested by those who it concerns and who can demonstrate the practical need?

**Comment by LJWatson** [comment] 2016-05-26 14:13
The case for type remaining conforming on `<ol>` seems good enough. Unless @stevefaulkner @travisleithead @adanilo or @arronei feel otherwise, suggest we close this issue. If someone wants to propose extending the type values, it's a discussion best had in collaboration with browser vendors in the <a href="https://www.w3.org/community/wicg/">Web Incubator CG</a>

**Comment by adanilo** [comment] 2016-05-27 01:57
SGTM, close and move further discussion to WICG makes sense.

**Comment by stevefaulkner** [comment] 2016-05-27 08:39
> SGTM, close and move further discussion to WICG makes sense.

+1

**Comment by rebecaruiz** [comment] 2016-05-27 08:46
> SGTM, close and move further discussion to WICG makes sense.

+1

**Comment by LJWatson** [comment] 2016-05-27 11:40
Thanks for the useful discussion everyone.

**Closed as completed by LJWatson** 2016-05-27 11:40 UTC
Labels: technical improvement, Should be deprecated?, i18n-comment

**Comment by aphillips** [comment] 2016-06-26 16:50
The I18N WG discussed this in our most recent [teleconference](https://www.w3.org/2016/06/23-i18n-minutes.html) and [actioned](https://www.w3.org/International/track/actions/535) me with adding a comment here. 

I18N understands the need for existing HTML documents to remain conformant. However, we oppose extending the list of keywords in favor of the CSS mechanism for the reasons cited by @r12a and others above. In addition, we continue to favor a health warning _against_ use of this feature. 

One concern is that, based on our experience in creating and maintaining [this document](http://w3c.github.io/predefined-counter-styles/), is that WICG work to incorporate different language or locale variations directly into the `ol` list of keywords would be complex and difficult to maintain in an interoperable way. In addition, I18N never favors features that provide convenient support only for a few languages/cultures.

Although we do not agree with this decision, I18N is deliberately not re-opening this issue and will not object to this decision.
