### ISSUE TITLE
deprecate style/type attribute

### ISSUE THREAD

**Issue by chaals** [w3c/html#1476] opened 2018-06-20 14:06 UTC
Is there any real style sheet that isn't CSS? The spec, and implementation in common browsers, seem to make that assumption, so the `type` attribute for the `style` element could be made obsolete.

see also https://github.com/whatwg/html/commit/9c612ac8641b5174849a2d3cb924fe662a8d3a09

**Comment by awwright** [comment] 2018-06-21 02:46
There's several languages that are intended to be a replacement for CSS:

* https://sass-lang.com/
* http://lesscss.org/

They typically offer a mechanism to compile into CSS to they can be debugged within a web browser. These cases don't always use the `type` attribute as intended, but this is to work around limitations in Web browsers, and should be considered a failure of tooling available within Web browsers, not of the `@type` attribute itself.

Sometimes media types also define sub-profiles of their language. For example, I-JSON is a subset of JSON that limits the range of numbers and other content to what's easily representable on most platforms. Even if Web browsers don't want to respect these sorts of features, there's good reason they may be used in authoring pipelines or by other tools.

**Comment by siusin** [comment] 2019-07-29 14:49
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.

**Closed as completed by siusin** 2019-07-29 14:49 UTC
Labels: match reality better, Should be deprecated?
