### ISSUE TITLE
Consider refactoring the document.domain attribute setter as a standalone algorithm

### ISSUE THREAD

**Issue by jcjones** [w3c/html#769] opened 2017-01-13 00:29 UTC
The [Web Authentication WG's draft](https://w3c.github.io/webauthn/#makeCredential) currently makes reference to the ["Relaxing the same-origin restriction" of the `document.domain` attribute setter](https://www.w3.org/TR/html51/browsers.html#relaxing-the-same-origin-restriction) as a way to let relying parties use foo.bar.com to generate scoped credentials for bar.com.

However, 1) the attribute setter procedure isn't documented as an algorithm - so we shouldn't call it like one, and 2) we need to override some of the ambient state within it, by changing some of the values to be passed as arguments.

We had started some work to [inline the procedure as an algorithim within our document](https://github.com/w3c/webauthn/pull/314), but [consensus is that it'd be better if we could avoid future divergence by refactoring this part of the HTML spec instead](https://github.com/w3c/webauthn/issues/256).

I'm not an expert on HTML, but as a starting point, it seems we'd want to take the existing `document.domain` attribute setter and make these adjustments:

1) Pass the Document that the procedure operates on as an argument
2) Pass the Active Sandboxing Flag Set as an argument
3) Retain the "given value" as an argument
4) Instead of modifying the Document supplied, return the result

I'm happy to start a PR for these changes if this is acceptable.

**Comment by jyasskin** [comment] 2017-02-10 20:57
I suspect it'll work to start the extracted algorithm at approximately step 4, and pass the `Document`'s origin as an argument instead of the `Document` itself.

Beyond that, I'd suggest you write the patch against https://github.com/whatwg/html instead of this repository, so that you're starting from a correct version of the algorithm (see #793).

**Comment by jcjones** [comment] 2017-02-10 23:17
Okay, will do @jyasskin - thanks. Should I re-open a similar (and linking) issue over at whatwg?

**Comment by jyasskin** [comment] 2017-02-10 23:34
It wouldn't hurt to have a separate issue in whatwg's repo, but I think you can get away with a raw PR that refers to this issue.

**Comment by equalsJeffH** [comment] 2017-02-23 17:52
this should be closed now that PR #2365 landed?

**Comment by jcjones** [comment] 2017-02-23 18:01
Sounds right. Thanks for the reminder!

**Comment by jyasskin** [comment] 2017-02-24 05:35
We should keep this open to track merging whatwg/html#2365 into HTML5.2. It doesn't block WebAuthn anymore, but the W3C editors still have a bit of work to do.

**Comment by chaals** [comment] 2017-02-24 08:14
This issue tracker is for W3C's spec, so the issue is still open.

**Closed as completed** 2017-12-01 16:46 UTC
Labels: Dependency Request
