### ISSUE TITLE
<select> tag should get placeholder= attribute and change the way it works

### ISSUE THREAD

**Issue by miketubby** [w3c/html#1125] opened 2017-12-22 14:05 UTC
Use of `<select> <option> <option> ... </select>` in forms and user interaction is clumsy and different from `<input>` fields, especially when wanting to maintain consistent look and feel.

The principal issue is that `<select> ... </select>` uses its first `<option>` as the default option and effectively as a placeholder and this results in a lot of complication with the use of 'hidden', 'disabled', etc attributes on the first option and difficulty with applying style (through CSS3) to get the first option to look like other placeholders on a page. In some cases it is impossible to find a combination of CSS selectors/pseudo-selectors that can target the first option in a consistent, cross-browser, cross-platform way.

The problem is that the first `<option>` is being two things, or being used for two things, at the same time (1) as a hint to the user (the job of a placeholder) and (2) an option value.  Because of this dual use we end up with negative logic with additional attributes ('hidden', 'disabled', etc.) attempting to repurpose it for single use.

I propose that the `<select>` tag be given the 'placeholder' attribute, such that when present the placeholder text appears in the dropdown area and all of the options are below in the dropdown. The placeholder text can be styled like any other placeholder on an `<input>` field.

Presence of the placeholder attribute would make the `<select>` work with new semantics while the lack of the placeholder attribute would use the existing semantics for backwards compatibility.

The new semantics would allow for simpler code, simpler CSS and better consistency across browsers.

Mike

**Comment by chaals** [comment] 2017-12-22 16:11
[I edited your comment. putting \` around the code makes it visible...]

Yes, the problem is pretty obvious and would be nice to fix.

But changing the behaviour is likely to be a bit complex - what is the migration path for authors and browsers.

I strongly suggest incubating this in the [W3C incubator group](https://discourse.wicg.io) to see if it gets some traction, before trying to add it to the spec.

**Comment by LJWatson** [comment] 2018-06-19 12:59
The `placeholder` attribute presents a hint or example of data to be entered into an `<input>` field. A `<select>` presents a finite set of options to the user, so `'placeholder` would not seem to solve the case described.

If there is support for the use case, it may be possible to propose/incubate a way to present the first option in a `<select>` in the way described. 

I think the custom of using `<option>...</option>` is to be discouraged though, and instead authors should be encouraged to use an appropriate `<label>` element for the `<select>`.

**Comment by garygreen** [comment] 2018-09-13 12:39
> A <select> presents a finite set of options to the user, so 'placeholder would not seem to solve the case 

It's bad UI to automatically force a default value upon a user - they may think an option has already been selected and not bother changing it. A common thing to do is make the first option say something like "<Please Select>" that doesn't force a default value and informs the user they need to select an option. This IS essentially a placeholder.

**Comment by garygreen** [comment] 2018-09-13 14:35
> If there is a safe default option, it can be best to have that as the deafult

In my experience, there is very rarely a good default option to have for selects - having a default option selected makes too many assumptions and also encourages the user to just skip that field.

Don't just take my word for it, look at this stackoverflow answer. Seems pretty common for a lot of people. https://stackoverflow.com/a/5859221/63523

**Comment by siusin** [comment] 2019-07-29 15:09
Thanks all.

We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).

If you filed this issue and you still think it is relevant, please open a [new issue](https://github.com/whatwg/html/issues) on the WHATWG repository and reference this issue (if there is useful information here). Before you open a new issue, please check for existing issues on the WHATWG repository to avoid duplication.

If you have questions about this, please open an issue on the [W3C HTML WG repository](https://github.com/w3c/htmlwg/issues/new) or send an email to public-html@w3.org.

**Closed by siusin** 2019-07-29 15:09 UTC
Labels: Feature request, Needs incubation, needs implementations, needs tests
