### ISSUE TITLE
thead element is not clear described content model: [was: Issue #1351]

### ISSUE THREAD

**Issue by siusin** [w3c/html#1530] opened 2018-07-20 16:41 UTC
Re-file [Issue #1351](https://api.github.com/repos/w3c/html/issues/1351) from [programmer3000](https://github.com/programmer3000).

from [programmer3000](https://github.com/programmer3000):

> `<thead>` element is not clear described content model:
> The `<thead>` element represents the block of rows that consist of the column labels (headers) 
> What is \"column labels (headers)\"? - it could be `<td>` or only `<th>` element inside `<tr>` which inside <thead>?
> https://www.w3.org/TR/html53/tabular-data.html#elementdef-thead

from [chaals](https://github.com/chaals):

> see also #819

**Comment by scottaohara** [comment] 2018-07-21 18:22
Being that this issue is essentially a duplicate of #819, and there's also open #583 which would touch upon this, I am going to close this particular issue as we won't lose anything here.

If anyone disagrees, then feel free to reopen...

**Closed as completed by scottaohara** 2018-07-21 18:22 UTC
Labels: duplicate
