### ISSUE TITLE
make <style> in <body> conforming

### ISSUE THREAD

**Issue by prlbr** [w3c/html#544] opened 2016-07-28 15:19 UTC
Please consider making `<style>` in `<body>` conforming.
- `<style>` in `<body>` apparently works in all major browsers
- it is useful for and indeed used by authors working with CMSs who don’t have access to the `<head>` at all or at least not easily on a page by page basis

See the corresponding [issue at WHATWG](https://github.com/whatwg/html/issues/1605) by @workguy66.

**Comment by chaals** [comment] 2016-07-31 21:52
See also #516, which is asking to _stop_ it conforming… I _think_ that in the current draft it is, but in any event, I think that we can cover this question within #516 - if you agree, please close this one.

**Comment by prlbr** [comment] 2016-08-02 07:20
As I understand it, https://github.com/w3c/html/issues/516 asks for an editorial change that would make a non-normative part of the spec be consistent with a normative part of the spec. It’s about consistency in the spec, not about which behaviour is desirable. So I think that’s neither the same nor the converse of this issue here.

But I see that the discussion in https://github.com/w3c/html/issues/516 actually goes in the direction of discussing which behaviour is desirable, so this question could indeed be covered there. But will it be? Or is someone going to say: “That’s not what this issue is about, please open a new one for your request”? Will people whom this issue here concerns find that other issue, if the other issue’s title and initial post don’t reflect what’s discussed there? Those are questions that make me feel uneasy about closing this one here. Not sure what to do.

**Comment by prlbr** [comment] 2016-08-02 07:37
To be clear, `<style>` in `<body>` shall work like `<style>` in `<head>`. The content of `<style>` shall not be written as text on the page. Millions of sites use it like this. For example, https://www.google.com/ does.

**Comment by adanilo** [comment] 2016-08-29 01:31
Agreed, this seems to be in widespread use so the reality of the web... Would you like to propose some text, or even a PR?

**Comment by chaals** [comment] 2016-10-03 09:54
I'm closing this as a duplicate of #516 - where the "trending conclusion" is to make style conforming in the body...

Thanks for raising it in this form though - I think it helped the discussion.

**Comment by AndySky21** [comment] 2016-12-01 02:43
Will it be clear for authors that the "effect" of style elements in body is
neither limited to the "scope" element, nor to the code after the style
element itself, but it will rather affect the whole document?

I'm especially concerned by the fact that  as style appears late in the
page, phenomena of FOUC can become harder and more likely.

Style in DOM is due to poor CMS coding rather than to real user practices.

**Comment by TakayoshiKochi** [comment] 2016-12-01 02:48
As @travisleithead commented in https://github.com/w3c/html/issues/516#issuecomment-251265453, if `<style>` is not allowed in `<body>`, `<style>` in shadow DOM won't work as expected.

**Comment by chaals** [comment] 2016-12-01 03:04
@AndySky21 given that browsers have already worked this way for a couple of decades, I suspect authors are not likely to start getting confused now.

**Comment by workguy66** [comment] 2016-12-01 09:22
@AndySky21 I disagree, to me it's pretty obvious that the style flickering is due to poor CMS coding, not that the style tag in body behaves the way that it is expected to behave.

**Comment by adanilo** [comment] 2017-01-13 04:59
Appears we have agreement to document it as conforming as per existing browser behaviour. @prlbr would you like to propose some text?

**Comment by prlbr** [comment] 2017-01-14 21:14
I guess not much text is needed, but the [definition box of the element](http://w3c.github.io/html/document-metadata.html#the-style-element) needs to be changed to allow `<style>` to be also where flow-content is expected and hence the [explanation of flow content](http://w3c.github.io/html/dom.html#flow-content) and maybe a few other references need to be updated?

I don’t feel ready to make these changes and would be happy if someone more knowledgable with the spec could take care of this. Thank you for the offer though, @adanilo!

**Comment by stevefaulkner** [comment] 2017-02-25 11:16
Also being discussed in whatwg world https://github.com/whatwg/html/issues/1605

**Comment by workguy66** [comment] 2017-02-27 09:16
Here's a fun idea to think about: Imagine if a browser comes along that
complies with the spec fully (meaning it won't support style in body at all)

**Comment by chaals** [comment] 2017-02-27 11:02
@workguy66 That's exactly what we think about. If the spec is ambiguous here, it isn't clear exactly what they would do. But it turns out that a browser that didn't allow `style` in the `body` wouldn't work on the Web.

We have an option to make it non-conforming but require browsers to handle it, and describe how to do that - this is what we do for a bunch of things, including appcache.

But there are use cases for doing it, and no clear reason I can see to *prohibit* it, although it's often not the best idea.

**Comment by AndySky21** [comment] 2017-02-27 12:18
Instead of being marked "non conforming but supported", which sounds quite strange, why not marking it "conforming with warning"? I.e. when validated (and in spec) it should be stated that putting style in body can be done, but as last resort only and underlining the problem that can be caused by that  (essentially FOUC if tons of content are loaded before style itself is parsed and applied).
It's up to the authors then to balance pros and cons (e.g. if style is parsed before the weighty stuff, or if style rules apply to dynamically inserted elements, it's quite safe)

After all, if UAs have learnt how to cope with that, now it's just a matter of usability trade-off. Not to mention all the CMSs, hubs and platforms which physically do not allow authors to insert whatever they want inside the document's head.

**Comment by ExplodingCabbage** [comment] 2017-02-28 21:25
@chaals and @workguy66, you say that a fully-compliant browser wouldn't support `<style>` in the body at all, but according to @domenic in https://github.com/whatwg/html/issues/1605#issuecomment-235961103:

> just to be very clear: this entire issue is not about changing browser behavior. ***The spec already requires, and browsers already implement, processing for `<style>` in body***. It works, albeit with the negative effects I discussed above.

(emphasis mine)

I'm not sure precisely what @domenic's reasoning is for how the spec requires this, and don't know whether there are relevant differences between the W3C and WhatWG specs in this regard, but it *seems* that he disagrees with you.

**Comment by workguy66** [comment] 2017-03-01 15:52
The spec requires the browsers to support it and then tells people not to
use it? Would make more sense if it warned people not to use it.

**Comment by chaals** [comment] 2017-03-29 17:30
`style` should also be listed as flow content, no? in dom.include at #flow-content

**Closed as completed** 2017-03-30 09:29 UTC
Labels: match reality better

**Comment by prlbr** [comment] 2017-05-03 10:19
The element box for [the style element](https://w3c.github.io/html/document-metadata.html#the-style-element) says for “Contexts in which this element can be used”:

- Where metadata content is expected.
- In a noscript element that is a child of a head element.

I think this should be changed to where flow content is expected.

**Comment by chaals** [comment] 2017-05-03 13:36
@prlbr agreed. I made a PR - feel free to review it...

**Comment by prlbr** [comment] 2017-05-03 15:38
Looks good, thank you!
