### ISSUE TITLE
Meta element already too redundant

### ISSUE THREAD

**Issue by LJWatson** [w3c/html#302] opened 2016-04-28 16:14 UTC
Migrated from <a href="https://www.w3.org/Bugs/Public/show_bug.cgi?id=29483">Bugzilla #29483</a>.

**Comment by prlbr** [comment] 2016-04-29 15:21
> […] so I assume parsers expect both and I have to supply both.

Actually, you do not have to supply any meta tags. Only very few are actually useful in every document, some might be useful for specialized pages and many are largely useless.

> Suggestion: Require in HTML5 that if an attribute's value is absent and a certain other value is present in the same file then interpret the metadata as if both were present and identical.

I think expecting parsers to conform to such a requirement would be illusionary and I would advise against requiring something that is as unlikely to happen broadly. An advice instead of a requirement might be fine though.

**Comment by chaals** [comment] 2016-05-02 17:26
The redundancy in terms of wanting to appeal to different consumers (think: schema.org data, dublin core, and say OGP) is outside our control - we mostly just provide a mechanism to add the data that you want to expose.

The part that is in the control of the Working Group is covered by #160, IMHO. I think this issue could be closed as a duplicate...

**Comment by travisleithead** [comment] 2016-05-02 19:50
FWIW, I agree with @Chaals, and I don't think we need a spec change for the parser here.

**Comment by chaals** [comment] 2016-05-03 11:25
This seems out of scope for HTML, since we don't constrain the values that people can use for metadata, deliberately.

**Comment by adanilo** [comment] 2016-05-04 00:54
I agree this is out of scope. Working as intended IMHO.

**Comment by Nick-Levinson** [comment] 2016-05-07 19:47
Whether to use many of these tags is debatable, but many website designers do not agree that almost none are needed, and neither do the editors of the HTML spec. In my site, I did not include any I did not think were required or useful and I still have a great many and with too much redundancy.

The problem here is that if you add one metatag for a purpose you consequently have to add others that serve the same purpose because different parsers are looking for different ones and won't share what's already online. For example, if you need a machine-readable copyright notice and that requires one meta tag, you now need five tags. So when every January you need to update the machine-readable copyright notice, you will need to update it in five places. And on it goes. So now, to make my website be findable in various ways, I have to write and maintain many more tags in total, and part of the reason for the expansion is that organizations looking for our meta elements are deciding they want their own meta tags on our sites. They'll likely ignore the old ones. So I have to keep using the old ones and also add the new ones.

The advice to reuse is already present, but the problem I illustrated needs something stronger than advice. It could be either a requirement or a technical solution, if we can come up with something for the latter.

Since HTML 5.1 sec. 4.2.5.2 refers to the WHATWG page and the WHATWG page requests reuse of existing values ("[w]e ask that you . . . avoid redundancy - if someone has already defined a name that does roughly what you want, please reuse it"), then this issue is within scope until either HTML or the WHATWG page is amended to delete the advice to reuse and restrain redundancy. I'm unaware of such a proposal.

Issue #160 is quite different. It's about link types and microformats, while this is about meta tags and redundancy. Neither issue is a duplicate of the other.

**Comment by prlbr** [comment] 2016-05-07 21:06
@Nick-Levinson 

> In my site, I did not include any I did not think were required or useful

Then maybe we could prevent misunderstandings by making more explicit that (most of) these tags are not required?

> The problem here is that if you add one metatag for a purpose you consequently have to add others that serve the same purpose because different parsers are looking for different ones and won't share what's already online. For example, if you need a machine-readable copyright notice and that requires one meta tag, you now need five tags.

What bad consequences do you fear would happen if you did not provide all these different meta tags for the same purpose? Do you think you would lose your legal rights? I’m quite sure that you won’t in most juristications.

**Comment by Nick-Levinson** [comment] 2016-05-07 21:46
You might (I have a more cautious attitude toward copyright notices than most programmers do, but the notice is supposed to be calculated to give notice to the intended audience and in machine-readable form if one form is no longer readable by all machines because other forms have partly displaced it then you have to provide those forms, too). But I could show roughly the same regarding the description metatag, which now has several forms. And likewise for other redundancy-affected tag sets.

Even if a tag is not required, if it's useful (and that's the intent), we often do well by adding it. Defining multiple tags that all are to provide the same description for the same purpose means we either get less accomplished from a description or we have to maintain more description-like tags.

**Comment by chaals** [comment] 2016-05-08 09:43
@Nick-Levinson said

> Issue #160 is quite different. It's about link types and microformats, while this is about meta tags and redundancy. Neither issue is a duplicate of the other.

Actually, I think the issues are similar. In the case or #160 we're looking at values for the `rel` attribute, and there is a long-standing practice of defining "canonical" values. Where these are implemented by e.g. browsers giving a shortcut to get to the contents or next page, we may have a relatively good chance of minimising redundancy.

In the case of what third parties will consume for `meta name=` values, I'm leaning toward the idea that we can offer advice in the spec about re-using things rather than adding to them, although there isn't any way to enforce that in practice unless browsers start automatically adding code to your pages - something that I highly doubt we would recommend. I've tagged this as editorial to look at what useful advice we can provide.

There are efforts, like Dublin Core and Schema.org to provide consistent values, but the point of a decentralised metadata mechanism that allows third parties to extend what they do is that they are allowed to create new things. Trying to enforce some kind of convergence through the HTML spec seems like the wrong place - these issues should be taken up with the various consumers of the data.

**Comment by Nick-Levinson** [comment] 2016-05-10 01:07
Maybe adding into the spec itself that reuse is preferred would help. The spec already links to the WHATWG wiki page and the advice to reuse is already on that wiki page, but maybe saying so in the spec itself would catch more programmers' attention.

I don't want anyone editing my pages. I agree on that. But a technical solution might not require that. User agents and parsers could be required to accept one metatag for others serving the same purpose. So, if Facebook's parser doesn't see Facebook's preferred description-like metatag but W3C's/WHATWG's is on the page, Facebook's parser could be required to accept the latter when the former is absent. That's provided Facebook chooses to comply, but that can be presumed if it's in the spec. If an author wants to have a different description just for Facebook, the author would write both Facebook and non-Facebook tags. If an author wants to have no description for Facebook while having one for Google's Web search engine, the author would write the Facebook tag with nothing or just a space between the content quotation marks while writing the W3C/WHATWG tag with the desired description.

Yes, it would be good to persuade the developers of consuming parsers, but I assume they already read the WHATWG page (although maybe I'm wrong and they didn't and that's why it should be in the spec).

The spec already says this: "If a metadata name is found to be redundant with existing values, it should be removed and listed as a synonym for the existing value." The WHATWG page is clearer for reuse, though.

It's good that the Dublin folks et al. are adding the new. The problem is with the redundancy. I suspect they may think it's new or that they have other meta tags that are new but with which they want a complete scheme with their brand and so they also create the redundant ones. Then it gets burdensome on us authors.

**Comment by chaals** [comment] 2016-06-13 08:03
> The spec already says this: "If a metadata name is found to be redundant with existing values, it should be removed and listed as a synonym for the existing value."

Having looked carefully, it's not clear that there is anything more to do in the HTML spec, pending a significant re-think of this part of HTML. I'm going to close this for now.

**Closed as completed by chaals** 2016-06-13 08:03 UTC
Labels: editorial
